#ifndef FLEXI_TENSOR_BACKEND_INTERNAL_H
#define FLEXI_TENSOR_BACKEND_INTERNAL_H

#include <stddef.h>
#include <stdint.h>

#include "flexi_tensor_backend.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_sv)(fnblas_vector_t*, const fnblas_vector_t*, const fnblas_scalar_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_ve)(fnblas_vector_t*, const fnblas_vector_t*, const fnblas_vector_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_vv)(fnblas_scalar_t*, const fnblas_vector_t*, const fnblas_vector_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_vr)(fnblas_scalar_t*, const fnblas_vector_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_vi)(fnblas_vector_t*, const fnblas_vector_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_mi)(fnblas_matrix_t*, const fnblas_matrix_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_me)(fnblas_matrix_t*, const fnblas_matrix_t*, const fnblas_matrix_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_mm)(fnblas_matrix_t*, const fnblas_matrix_t*, const fnblas_matrix_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_mmv)(fnblas_matrix_t*, const fnblas_matrix_t*, const fnblas_matrix_t*, const fnblas_vector_t*);
typedef flexi_tensor_error_t (*_flexi_tensor_backend_kernel_op_mmm)(fnblas_matrix_t*, const fnblas_matrix_t*, const fnblas_matrix_t*, const fnblas_matrix_t*);

typedef _flexi_tensor_backend_kernel_op_sv _flexi_tensor_backend_kernel_op_sv_add;
typedef _flexi_tensor_backend_kernel_op_sv _flexi_tensor_backend_kernel_op_sv_sub;
typedef _flexi_tensor_backend_kernel_op_sv _flexi_tensor_backend_kernel_op_sv_mul;
typedef _flexi_tensor_backend_kernel_op_sv _flexi_tensor_backend_kernel_op_sv_div;
typedef _flexi_tensor_backend_kernel_op_sv _flexi_tensor_backend_kernel_op_sv_max;
typedef _flexi_tensor_backend_kernel_op_sv _flexi_tensor_backend_kernel_op_sv_min;
typedef _flexi_tensor_backend_kernel_op_ve _flexi_tensor_backend_kernel_op_ve_add;
typedef _flexi_tensor_backend_kernel_op_ve _flexi_tensor_backend_kernel_op_ve_sub;
typedef _flexi_tensor_backend_kernel_op_ve _flexi_tensor_backend_kernel_op_ve_mul;
typedef _flexi_tensor_backend_kernel_op_ve _flexi_tensor_backend_kernel_op_ve_div;
typedef _flexi_tensor_backend_kernel_op_ve _flexi_tensor_backend_kernel_op_ve_max;
typedef _flexi_tensor_backend_kernel_op_ve _flexi_tensor_backend_kernel_op_ve_min;
typedef _flexi_tensor_backend_kernel_op_vv _flexi_tensor_backend_kernel_op_vv_dot;
typedef _flexi_tensor_backend_kernel_op_vr _flexi_tensor_backend_kernel_op_vr_sum;
typedef _flexi_tensor_backend_kernel_op_vr _flexi_tensor_backend_kernel_op_vr_mean;
typedef _flexi_tensor_backend_kernel_op_vr _flexi_tensor_backend_kernel_op_vr_max;
typedef _flexi_tensor_backend_kernel_op_vr _flexi_tensor_backend_kernel_op_vr_min;
typedef _flexi_tensor_backend_kernel_op_vi _flexi_tensor_backend_kernel_op_vi_exp;
typedef _flexi_tensor_backend_kernel_op_mi _flexi_tensor_backend_kernel_op_mi_transpose;
typedef _flexi_tensor_backend_kernel_op_me _flexi_tensor_backend_kernel_op_me_add;
typedef _flexi_tensor_backend_kernel_op_me _flexi_tensor_backend_kernel_op_me_sub;
typedef _flexi_tensor_backend_kernel_op_me _flexi_tensor_backend_kernel_op_me_mul;
typedef _flexi_tensor_backend_kernel_op_me _flexi_tensor_backend_kernel_op_me_div;
typedef _flexi_tensor_backend_kernel_op_mm _flexi_tensor_backend_kernel_op_mm_matmul;
typedef _flexi_tensor_backend_kernel_op_mmv _flexi_tensor_backend_kernel_op_mmv_axpy;
typedef _flexi_tensor_backend_kernel_op_mmm _flexi_tensor_backend_kernel_op_mmm_axpy;

extern flexi_tensor_backend_t _flexi_tensor_current_backend;

#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_sv_add op_sv_add
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_sv_sub op_sv_sub
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_sv_mul op_sv_mul
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_sv_div op_sv_div
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_sv_max op_sv_max
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_sv_min op_sv_min
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_ve_add op_ve_add
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_ve_sub op_ve_sub
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_ve_mul op_ve_mul
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_ve_div op_ve_div
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_ve_max op_ve_max
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_ve_min op_ve_min
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_vv_dot op_vv_dot
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_vr_sum op_vr_sum
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_vr_mean op_vr_mean
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_vr_max op_vr_max
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_vr_min op_vr_min
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_vi_exp op_vi_exp
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_mi_transpose op_mi_transpose
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_me_add op_me_add
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_me_sub op_me_sub
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_me_mul op_me_mul
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_me_div op_me_div
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_mm_matmul op_mm_matmul
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_mmv_axpy op_mmv_axpy
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER__flexi_tensor_backend_kernel_op_mmm_axpy op_mmm_axpy
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER_IMPL(kernel_type) FLEXI_TENSOR_BACKEND_KERNEL_MEMBER_##kernel_type
#define FLEXI_TENSOR_BACKEND_KERNEL_MEMBER(kernel_type) FLEXI_TENSOR_BACKEND_KERNEL_MEMBER_IMPL(kernel_type)
#define FLEXI_TENSOR_BACKEND_KERNEL_GET(kernel_type) ((kernel_type)_flexi_tensor_current_backend.FLEXI_TENSOR_BACKEND_KERNEL_MEMBER(kernel_type))

#ifdef __cplusplus
}
#endif

#endif // FLEXI_TENSOR_BACKEND_INTERNAL_H
